### ISSUE TITLE
migrate woocommerge integration from ERPNext to this app

### ISSUE THREAD

**Issue by ankush** [frappe/ecommerce_integrations#108]
- [x] New module
- [x] Basic migration (doctypes, utils)
- [x] Use ecommerce item instead of custom fields
- [x] Write patch to migrate existing users
- [ ] Remove integration from core

**Comment by s-aga-r** [comment]
`woo-commerce` integration is deprecated in ERPNext v15.

ref: https://github.com/frappe/erpnext/pull/37015
