### ISSUE TITLE
Shopify: Decouple Shopify Customer from ERPNext Customer

### ISSUE THREAD

**Issue by SilentHunter124** [frappe/ecommerce_integrations#11]
Currently the shopify customer database is a huge mess simply after 3 months of operations. A lot of duplicate accounts were created and it is heavily discussed here: https://community.shopify.com/c/Shopify-Discussion/Merge-Customers/td-p/912491/page/7

**Current behaviour:**

Shopify Sync Compares Shopify Customer ID of an ERPNext Customer with Shopify Customer ID of incoming new Order. This will lead in case no registration is default checkout behaviour to multiple duplicates in ERPNext.

**Idea:**

Introduce a shopify setting "Customer Anchors" with list values "Shopify Customer ID","E-Mail","Phone","E-Mail&Surname&Lastname" (last one has biggest safety) which will be used to search for existing ERPNext Customers and reuse it.
Don't forget to update billing and shipping address for the incoming order as it may differ only for this incoming order.

This is just an idea. And for discussion. What do you think about that?

Regards

**Comment by ankush** [comment]
I don't think it would be wise to "merge" customers when Shopify themselves don't do it. 😅  This will break possible future features that rely on somehow uniquely linking ERPNext customers to Shopify customers (which is only possible through the ID field)

**Comment by SilentHunter124** [comment]
That is true, I am just thinking about, if there is another way of not flooding erpnext customer database then with every new anonymous order. Do you have an idea?

**Comment by ankush** [comment]
There's an option for specifying the Customer group, the best thing I can suggest is to ignore that group by filtering it out.
