### ISSUE TITLE
Woocommerce integration requires to modify "item_code"

### ISSUE THREAD

**Issue by tecnofoodmx** [frappe/ecommerce_integrations#111]
In order to be able to integrate wocommerce with erpnext, the item code should have the following format: "wocommerce - " + "wocommerce_id".

This is highly inconvenient, specially when trying to integrate woocommerce to an existing erpnext company, since it requires either o of the following scenarios:
1- Modify an existing item code: theres plenty of room for operational disaster when trying to change item codes "on the fly". Completely unacceptable for a running business,
2- Create special items just to interact with wocommerce: much of the point of doing the integration is lost since it would require to manage special stock o to rework the generated sales order to match the actual item codes.

¿is it possible to fix this such that woocommerce interacts with ERPNext via the woocommerce_id (in a similar way as the shopify integration worked (by the way, Shopify worked beautifully)?

**Comment by ankush** [comment]
@aaronmenezes

**Comment by s-aga-r** [comment]
`woo-commerce` integration is deprecated in ERPNext v15.

ref: https://github.com/frappe/erpnext/pull/37015
