### ISSUE TITLE
Shopify: Enable a description text for the final invoice on each tax line setting

### ISSUE THREAD

**Issue by SilentHunter124** [frappe/ecommerce_integrations#13]
Currently it is only possible to map shopify tax title to account. But on the invoice, the name of the account head is displayed, as it uses the default description from there. 

I think it makes sense to enter a description per each of these lines, that is displayed and used in the invoice templates (should actually be already existing field description):

![image](https://user-images.githubusercontent.com/1576808/120531840-58362980-c3df-11eb-8546-c29b0e0e0021.png)

What do you think?

**Comment by ankush** [comment]
Sounds like a good idea. If anyone's willing to pick this up it's mostly just 2 small changes:

- Add field in child doctype
- Change description to consider specified field first, fallback to default if not available

https://github.com/frappe/ecommerce_integrations/blob/b56e85716df9615900b1bbccee3c2ff0ee68eb66/ecommerce_integrations/shopify/order.py#L160

**Comment by SilentHunter124** [comment]
I tried my very best as I am really new to this framework, please have a look: #15

**Comment by ankush** [comment]
@SilentHunter124 

To manually force a sync you can send JSON data as dict to the function that processes sales orders. There's test util too which I recently added for faking Shopify requests, but that still needs to be expanded to cover orders.

Thanks for the PR BTW, I left some suggestions. If you're unable to do the changes on PR then let me know, I'll push the changes and merge them in.

**Comment by SilentHunter124** [comment]
I just did the changes, requested, no problem you're welcome :)
