### ISSUE TITLE
ERPNext does discounts on Grand Total while Shopify does them on Net Total

### ISSUE THREAD

**Issue by prices** [frappe/ecommerce_integrations#154]
Any discounts on an order will sync totally wrong because all of the taxes will be calculated wrong. Then ERPNext uses this wrong total in all of the other documents, including the payments sync’d.

Example:
Order Net Total: $100
Discount: $20
Tax 10%

Shopify:
$100 - $20 = $80 (Discount on Net Total)
$80 * 1.10 = $88 (Tax Calculation)
Order total: $88

ERPNext:
$100 * 1.10 = $110 (Tax Calculation)
$110 - $20 = $90 (Discount on Grand Total)

So everything in ERPNext is off. ERPNext even logs a payment of $90 instead of $88 which is what the customer actually paid.

So I have to then go in and cancel and amend any orders that have a discount on them, including changing all the payment information and sales invoices.

I have tried changing the default of the "Apply Additional Discount On" field to "Net Total" instead of "Grand Total".  I changed it in Delivery Note, Sales Order, and Sales Invoice.

I am using the latest ERPNext v13.17.1  with the latest ecommerce_integrations.

**Comment by prices** [comment]
This is on a self hosted site.  I used:

bench get-app ecommerce_integrations --branch main

To install ecommerce_integrations.

One anomaly is that it still says "Shopify Integration will be removed from ERPNext in Version 14. Please install Ecommerce Integrations app to continue using it." at the top of the Shopify settings.

**Comment by prices** [comment]
Here is the thread I started on the ERPNext forum:

https://discuss.erpnext.com/t/erpnext-does-discounts-on-grand-total-while-shopify-does-them-on-net-total/83699

**Comment by ankush** [comment]
@prices can you share:
1. Order's JSON (go to "Ecommerce integration log" and find order by doing "Like" search on request data field)
2. Shopify's tax computation
3. ERPNext's tax computation
4. Version number of ecommerce_integration app you're using. 


This integration removes tax and discount from base price and applies tax at actual value (not percentage). So I am not sure how the "multiplication of tax rate" even applies here.

**Comment by prices** [comment]
It will take me a little bit to figure out how to get example to you, as I can't send you customer data.  I will have to mock something up, probably.

Here is the version I am using:
```
erpnext@mfg:~/frappe-bench/apps/ecommerce_integrations$ git branch
* main
erpnext@mfg:~/frappe-bench/apps/ecommerce_integrations$ git log
commit f4908fddb1126620aac7b1f0ae9c45c49482de8e (grafted, HEAD -> main, tag: v1.5.0, upstream/main)
Author: Ankush Menat <ankush@frappe.io>
Date:   Fri Dec 17 19:12:28 2021 +0530

    chore: bump version
erpnext@mfg:~/frappe-bench/apps/ecommerce_integrations$ git status
On branch main
Your branch is up to date with 'upstream/main'.

nothing to commit, working tree clean

```

**Comment by prices** [comment]
I suspect it is using the built in shopify rather than the added on app.  I found the equivalent code sample to what you posted above and it looks like:

```
                taxes.append({
                        "charge_type": _("On Net Total"),
                        "account_head": get_tax_account_head(tax),
                        "description": "{0} - {1}%".format(tax.get("title"), tax.get("rate") * 100.0),
                        "rate": tax.get("rate") * 100.00,
                        "included_in_print_rate": 1 if shopify_order.get("taxes_included") else 0,
                        "cost_center": shopify_settings.cost_center
                })

```
So why it is using the built in instead of the add on?
Thanks!

**Comment by ankush** [comment]
maybe you forgot to disable old one? 🤔 I know this is a bit messy and confusing. 😓 

There are two settings old one called "Shopify Setting**S**" (plural) and new one called "Shopify Setting"

Fixing this confusion is in the backlog.

**Comment by prices** [comment]
How do I disable the old one?  I thought it was just a question of unchecking the "Enable Shopify" checkbox in the "Shopify SettingS".  Is there someplace else it needs to be disabled?

**Comment by prices** [comment]
I think I found it.  I will try it and get back to you.

Thanks!

**Comment by prices** [comment]
I got it up and running on the correct code.  This can be closed.
