### ISSUE TITLE
If is_sales_item is set to default to false shopify item sync can't create item in erpnext

### ISSUE THREAD

**Issue by prices** [frappe/ecommerce_integrations#157]
I set is_sales_item to false because less than 10% of our items are sales items.

This causes the a "item is not a sales item" error when it tries to create the item.  If the item is on Shopify it seems is_sales_item could be forced to true when the item is created.

**Comment by ankush** [comment]
This should be default in e-commerce item creation util I think.

I don't think any item being used by integrations would be "non sales" item.

**Comment by prices** [comment]
If you point me to the area of the code this should go in I can probably do a pull request.

**Comment by ankush** [comment]
https://github.com/frappe/ecommerce_integrations/blob/8e9f6735fc3ca021ce7977264856c092db79cd57/ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_item/ecommerce_item.py#L148
