### ISSUE TITLE
Module import failed for Test Runner

### ISSUE THREAD

**Issue by vcavel** [frappe/ecommerce_integrations#159]
Hi people,

I'm having a very hard time setting up ecommerce_integrations in order to connect shopify to my erpnext.

First of all, I've got this issue when installing the app :

```
erp@vps-8377dec2:~/erp_bench$ bench --site erp.singe-savant.com install-app ecommerce_integrations
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`


Installing ecommerce_integrations...
Updating DocTypes for ecommerce_integrations: [========================================] 100%
An error occurred while installing ecommerce_integrations:
Module import failed for Test Runner (frappe.core.doctype.test_runner.test_runner Error: No module named 'frappe.core.doctype.test_runner.test_runner')
```

Do you have any idea ?

Ecommerce Integrations: v1.5.0 (main)
ERPNext: v13.18.0 (version-13)
Frappe Framework: v13.18.0 (version-13)

Thanks

**Comment by ankush** [comment]
can't really tell from this why it's happening. Test runner is not imported in any production code. Can you try running in verbose mode (assuming this is just a test site).

`bench --verbose --site.... yourcommands`

**Comment by ankush** [comment]
closing this. 

Not enough info to reproduce the bug and haven't noticed this anywhere else 😅 

Add more info and I'll look into it.
