### ISSUE TITLE
If the Shopify total for an order is $0 the order won't sync

### ISSUE THREAD

**Issue by prices** [frappe/ecommerce_integrations#162]
We get the error "Paid Amount is mandatory".

We sometimes give away products or training as a thank you.  If these are alone on a shopify order the order won't sync.  The paid amount is $0 but that is also the amount due on the order.

Can logic be put in to check to see if paid amount and due amount match, and if so the order is valid, even if that amount is $0?

**Comment by ankush** [comment]
need to avoid attempting to make payment entry for 0-valued orders I think:

https://github.com/frappe/ecommerce_integrations/blob/8e9f6735fc3ca021ce7977264856c092db79cd57/ecommerce_integrations/shopify/invoice.py#L65-L74

**Comment by prices** [comment]
Something like:

--- a/ecommerce_integrations/shopify/invoice.py
+++ b/ecommerce_integrations/shopify/invoice.py
@@ -51,7 +51,8 @@ def create_sales_invoice(shopify_order, setting, so):
                set_cost_center(sales_invoice.items, setting.cost_center)
                sales_invoice.insert(ignore_mandatory=True)
                sales_invoice.submit()
-               make_payament_entry_against_sales_invoice(sales_invoice, setting, posting_date)
+               if sales_invoice.grand_total > 0:
+                       make_payament_entry_against_sales_invoice(sales_invoice, setting, posting_date)
 
                if shopify_order.get("note"):
                        sales_invoice.add_comment(text=f"Order Note: {shopify_order.get('note')}")

**Comment by ankush** [comment]
I guess that should be enough, can you test if that fixed issue for your and raise a PR?

**Comment by prices** [comment]
It worked for me.  I will create a pull request.
