### ISSUE TITLE
Shopify webhook is not processed

### ISSUE THREAD

**Issue by pts211** [frappe/ecommerce_integrations#169]
Orders and other webhook events are failing to process from Shopify into ERPNext through the ecommerce_integration plugin. 

To investigate I recorded the webhook request that was being sent to the ERPNext server and am recreating with Postman. Issuing the post request is giving a: 500 INTERNAL SERVER ERROR with the payload quoted below. 

Please let me know if there are more details I can provide to assist this getting a timely resolution.

````
{
    "exception": "TypeError: Object of type bytes is not JSON serializable",
    "exc": "[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 68, in application\\n    response = frappe.api.handle()\\n  File \\\"apps/frappe/frappe/api.py\\\", line 55, in handle\\n    return frappe.handler.handle()\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 31, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 68, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1208, in call\\n    return fn(*args, **newargs)\\n  File \\\"apps/ecommerce_integrations/ecommerce_integrations/shopify/connection.py\\\", line 98, in store_request_data\\n    hmac_header = frappe.get_request_header(\\\"X-Shopify-Hmac-Sha256\\\")\\n  File \\\"apps/ecommerce_integrations/ecommerce_integrations/shopify/connection.py\\\", line 128, in _validate_request\\n    frappe.logger(\\\"pauls-log\\\").info(\\\"2-3\\\")\\n  File \\\"apps/ecommerce_integrations/ecommerce_integrations/shopify/utils.py\\\", line 19, in create_shopify_log\\n    return create_log(module_def=MODULE_NAME, **kwargs)\\n  File \\\"apps/ecommerce_integrations/ecommerce_integrations/ecommerce_integrations/doctype/ecommerce_integration_log/ecommerce_integration_log.py\\\", line 57, in create_log\\n  File \\\"/usr/lib/python3.8/json/__init__.py\\\", line 234, in dumps\\n    return cls(\\n  File \\\"/usr/lib/python3.8/json/encoder.py\\\", line 201, in encode\\n    chunks = list(chunks)\\n  File \\\"/usr/lib/python3.8/json/encoder.py\\\", line 438, in _iterencode\\n    o = _default(o)\\n  File \\\"/usr/lib/python3.8/json/encoder.py\\\", line 179, in default\\n    raise TypeError(f'Object of type {o.__class__.__name__} '\\nTypeError: Object of type bytes is not JSON serializable\\n\"]"
}
````

**Comment by ankush** [comment]
You can't recreate the shopify requests using Postman. Their requests have HMAC headers that is used for verifying that request was genuinely made by shopify and not someone else 😄 


https://shopify.dev/apps/webhooks#webhook-headers


Share the exact error log instead (check "e-commerce integration log"

**Comment by pts211** [comment]
I am including all the headers which should be recreating it fine. But I'm happy to share logs, however, I'm not seeing a specific e-commerce log. Is it a dedicated log file? Or is an entry in one of the generic log files?

**Comment by ankush** [comment]
It's a doctype called "Ecommerce integration log"

**Comment by pts211** [comment]
Well, that's embarrassing. For some reason the default filter for that page was "queued" and was hiding the errors from me. I discovered it was failing due to not mapping tax categories. Thank you for pointing me in the right direction!
