### ISSUE TITLE
Shopify "Sync Old Orders" problem

### ISSUE THREAD

**Issue by jere55304** [frappe/ecommerce_integrations#193]
To re-sync invalid and errored Shopify/ERPNext sales order items in ERPNext I goto Shopify Settings, "Sync Old Orders", after entering date range, saving, and looking at Ecommerce Integration Log, it shows "migrate_from_old_connector" with queued status.  Is this correct?  Not seeing my items in the log being processed after fixing.

**Comment by ankush** [comment]
It takes a while to begin processing old orders. Usually it's triggered within 1 hour.
