### ISSUE TITLE
Unable to import ecommerce item if system manager role is disabled.

### ISSUE THREAD

**Issue by pallavi-choubey** [frappe/ecommerce_integrations#211]
Hi All,

We are using the template and variant item. So after discussion, it was suggested as a workaround by Frappe team to manually upload ecommerce items to avoid duplication of items whenever a new SO syncs with the ERP. Currently, this can be done only by if System Manager role is enabled. If this permission can be given to another role, then it would help ease the operations. As we cannot give system manager role for every user who imports data.

Steps to replicate:
1. Go to the doctype list --> search for Ecommerce Item.
2. Then click on import option from the Ecommerce Item list doctype.
3. The data import is being done. 

Observation:
1. Here while doing the data import for ecommerce items, Currently, this can be done only by System Manager.

Expectation:
1. If this permission can be given to another role, then it would help ease the operations. 	

Thankyou.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/60428390/194801920-a318a1e6-7599-4056-8fe0-38c936640f1b.png">

**Comment by ankush** [comment]
@pallavi-choubey you can grant these roles using role permission manager. No need to change anything in code.

**Comment by pallavi-choubey** [comment]
Hi Ankush,

We have granted all permission to some roles for Data Import doctype and ecommerce item doctype. As per the attached screenshot we can't provide submit permission for the ecommerce item. So any User without system manager role can upload but can't submit. Please let me know your thoughts on this.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/60428390/194819619-370bb4ce-6d7f-49e2-a61e-930065d2a0e2.png">


Thanks.

**Comment by ankush** [comment]
@pallavi-choubey not sure why you need submit permission, this doctype is not submittable type.

**Comment by pallavi-choubey** [comment]
Hi Ankush,

We need to submit the Ecommerce item separately through Data import because we work with template and variant items and while the order sync the existing items were not syncing and creating new items. We discussed with your Team and post discussion it was decided to create the items through Data Import. Currently we have given all permission for Data Import and Ecommerce Item and observed that only the System manager is able to Submit.

Thanks.

**Comment by ankush** [comment]
@pallavi-choubey you don't need to SUBMIT them. Ecommerce item is not a submittable doctype. Just importing them is enough!
