### ISSUE TITLE
Amazon SP-API Sync Products not working

### ISSUE THREAD

**Issue by olegcarguy** [frappe/ecommerce_integrations#230]
I'm running a new fresh install of erpnext 14 on prem on ubuntu 22.04 with the ecommerce_integration module.  After setting up all of my Amazon SP-API credentials, I click save and settings are saved successfully.  However, when I try to Sync Products, nothing happens.  No errors are generated and no products are synced.  I've checked logs and they are empty.  Please help.

**Comment by s-aga-r** [comment]
@olegcarguy This should be resolved in the latest release. Closing this, reopen if not fixed after the update.
