### ISSUE TITLE
WooCommerce intergation - Currency not synced

### ISSUE THREAD

**Issue by abojasem911** [frappe/ecommerce_integrations#245]
we have enabled the integration for ERPNext and Woo-commerce and the orders and items sync with no issues but as our woo-commerce is multi-currency the currency of the orders are  not synchronized into EPRNext properly once the sales order is auto-created. need to consider this issue and find a fix or a work-around for it.

**Comment by s-aga-r** [comment]
`woo-commerce` integration is deprecated in ERPNext v15.

ref: https://github.com/frappe/erpnext/pull/37015
