### ISSUE TITLE
Shopify Version Issue

### ISSUE THREAD

**Issue by vorasmit** [frappe/ecommerce_integrations#252]
Version: 2022-04 is no longer supported

https://github.com/frappe/ecommerce_integrations/blame/develop/ecommerce_integrations/shopify/constants.py#L9

Error:
```
Traceback (most recent call last):
  File "env/lib/python3.9/site-packages/shopify/api_version.py", line 17, in coerce_to_version
    return cls.versions[version]
KeyError: '2022-04'
```

Supported Versions: https://shopify.dev/docs/api/release-notes

**Comment by rtdany10** [comment]
Need to switch to version 2022-10. Ref: https://shopify.dev/changelog/support-for-api-version-2022-04-extended-to-june-30-2023-1

@ankush

**Comment by vorasmit** [comment]
It will be deprecated further in 3 months. As per Shopify, they release version every 3 months and are deprecated in a year.

Best if its upgraded to 2023-04 or 2023-07.

**Comment by rtdany10** [comment]
I had locally changed the version to 2022-10 and nothing seems to break so far. But I have not tested thoroughly, else would've sent a PR. And yes, we should consider upgrading to the latest version.

**Comment by ankush** [comment]
https://github.com/frappe/ecommerce_integrations/pull/254 

@rtdany10 / @vorasmit can you check it out? I checked all main APIs they don't seem to have breaking change.
