### ISSUE TITLE
Failed to register webhooks with Shopify.

### ISSUE THREAD

**Issue by Akshat-10** [frappe/ecommerce_integrations#264]
Failed to register webhooks with Shopify.
Please check credentials and retry. Disabling and re-enabling the integration might also help
![Screenshot from 2023-08-21 17-51-18](https://github.com/frappe/ecommerce_integrations/assets/65578512/c7a1583c-855d-46a1-857f-0a24dc4d842f)

![Screenshot from 2023-08-21 17-56-06](https://github.com/frappe/ecommerce_integrations/assets/65578512/c120092a-073c-43fc-a2ab-d5d9c9af165f)

**Comment by ankush** [comment]
You can't register webhooks on localhost.

**Comment by Akshat-10** [comment]
> 

Thanks bhai
