### ISSUE TITLE
Move WooCommerce integration from frappe/erpnext to here

### ISSUE THREAD

**Issue by prices** [frappe/ecommerce_integrations#269]
Currently support is still in the main erpnext.  It is deprecated in version 15, so support there is going away.

It should be here so that people (like me) who are on WooCommerce will be covered.

Thanks!

**Comment by s-aga-r** [comment]
https://github.com/frappe/erpnext/pull/37015

**Comment by prices** [comment]
I did find https://github.com/libracore/WooCommerceConnector .  However it doesn't work out of the box for me.  I am working on fixing it at https://github.com/hugllc/WooCommerceConnector .

**Comment by davygarg** [comment]
Mine is working. I think i did some modification long time back :

https://github.com/davygarg/WooCommerceConnector
