### ISSUE TITLE
Shopify Warehouse Mapping Limitation

### ISSUE THREAD

**Issue by ahandlen** [frappe/ecommerce_integrations#277]
Ecommerce Int Version 1.19.1
ERPNext V14.45.3
Frappe FW 14.53.1

When in Shopify Settings, if more than 50 locations exist in Shopify they will not load into the Shopify Warehouse Mapping table, only the first 50 records are pulled.

Any idea how I can get around this? Shopify supports up to 1000 locations. Appreciate any insight

**Comment by ankush** [comment]
I didn't know they supported that many locations 😱 

It can be supported by paginating and fetching all locations here: https://github.com/frappe/ecommerce_integrations/blob/ace843fde3c653ed53c82f283e49fdf9aba457bf/ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.py#L90


This is how pagination usually works:
https://github.com/frappe/ecommerce_integrations/blob/ace843fde3c653ed53c82f283e49fdf9aba457bf/ecommerce_integrations/shopify/order.py#L420

**Comment by ahandlen** [comment]
> I didn't know they supported that many locations 😱
> 
> It can be supported by paginating and fetching all locations here:
> 
> https://github.com/frappe/ecommerce_integrations/blob/ace843fde3c653ed53c82f283e49fdf9aba457bf/ecommerce_integrations/shopify/doctype/shopify_setting/shopify_setting.py#L90
> 
> This is how pagination usually works:
> 
> https://github.com/frappe/ecommerce_integrations/blob/ace843fde3c653ed53c82f283e49fdf9aba457bf/ecommerce_integrations/shopify/order.py#L420

Hi Ankush,

Thank you for the insight/input. Admittedly I am not very experienced on the end of Frappe, would you be willing to explain a little further as to how I force it to load multiple pages rather than only the first 50 results? I really appreciate your input.

**Comment by ankush** [comment]
I pushed the change. See if it fixes the problem for you. Fetching and saving doc with 1000 items might take some time.

**Comment by ahandlen** [comment]
> I pushed the change. See if it fixes the problem for you. Fetching and saving doc with 1000 items might take some time.

I'll run through it now and let you know. I only have about 250 locations right now so we will see.

**Comment by ankush** [comment]
It's just not implemented in code. ERPNext does have support for group warehouse. 

IIRC I did implement it for unicommerce and since the logic is very similar it can work for Shopify too. I don't have time to work on it or verify it right now though.

**Comment by ankush** [comment]
https://github.com/frappe/ecommerce_integrations/blob/3453b0b27a8d4e460525e9090b3ed5cb43c2f4c4/ecommerce_integrations/controllers/inventory.py#L36

**Comment by ahandlen** [comment]
> It's just not implemented in code. ERPNext does have support for group warehouse.
> 
> IIRC I did implement it for unicommerce and since the logic is very similar it can work for Shopify too. I don't have time to work on it or verify it right now though.

Ah I see, was just curious as it seemed to be a fairly common restriction across doc-types from what i've seen. Good to know that it is possible.

Pagination worked to get all 250 location references in. Although I see some API errors against the call

"47795576963390,93342957886,Failed,Response(code=429, body="b'{"errors":"Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service."}'", headers={'Date': 'Thu, 09 Nov 2023 20:57:02 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'CF-Ray': '8238f73d3ee352b3-LAX', 'CF-Cache-Status': 'DYNAMIC', 'Retry-After': '2.0', 'Strict-Transport-Security': 'max-age=7889238', 'Content-Security-"

Is the sync only set on a timer (i.e. 5-60 mins) to respect the call limits without thought towards total # of items? It is my understanding the recommended sync time is 30 or 60 minutes but this error is reproducible even at the longest time allotment.
