### ISSUE TITLE
Shopify API Key removed

### ISSUE THREAD

**Issue by SilentHunter124** [frappe/ecommerce_integrations#30]
Hi @ankush ,

was it accidently or for reason? The Shopify API key was removed?

**Comment by ankush** [comment]
I removed it in this commit https://github.com/frappe/ecommerce_integrations/commit/58e8a6e0adf4f51cd6a48febb482a8547107aa6a  because Shopify SDK doesn't need it: https://github.com/Shopify/shopify_python_api#private-apps 

Reopen if there are any issues caused by it.
