### ISSUE TITLE
Unable to access Shopify Settings Page in ERPNext: v15.15.0 

### ISSUE THREAD

**Issue by codewithjaspreet** [frappe/ecommerce_integrations#313]
I am testing the shopify ecommerce integration on my self hosted site.
Installed the ecommerce_integrations app  via bench  but now unable  to access the shopify settings page for credential setup

removing 'S' or other alternatives present in issues dosen't work 

Please help me figure out this, below are the snapshot for the same
 
<img width="1369" alt="Screenshot 2024-04-22 at 12 19 01 PM" src="https://github.com/frappe/ecommerce_integrations/assets/85099922/21fd3558-01ee-4ed9-918b-ccaa3df0c677">
<img width="1315" alt="Screenshot 2024-04-22 at 12 19 29 PM" src="https://github.com/frappe/ecommerce_integrations/assets/85099922/d65d6f68-4859-4291-bd94-8cf1972fd573">
<img width="1006" alt="Screenshot 2024-04-22 at 12 19 36 PM" src="https://github.com/frappe/ecommerce_integrations/assets/85099922/af1d92f4-4627-4ce2-b1b2-87cd18cd26b4">

<img width="961" alt="Screenshot 2024-04-22 at 12 19 46 PM" src="https://github.com/frappe/ecommerce_integrations/assets/85099922/1ef469c8-4d03-4e9e-913a-681ab4c0aeb2">

**Comment by ankush** [comment]
Remove `s` at end it's singular for weird compatibility reasons.
