### ISSUE TITLE
Unable to fetch new sales order

### ISSUE THREAD

**Issue by vineyrawat** [frappe/ecommerce_integrations#84]
Hi, I'm working with latest version of frappe with ecommerce_integrations but it is not syncing latest orders created in shopify.
Please help us out.
Thanks

**Comment by ankush** [comment]
Any errors in "Ecommerce integration log"?

Did you see any warnings while setting it up?

**Comment by vineyrawat** [comment]
@ankush There is no error or warning in logs.
